### ISSUE TITLE
Color issue with Twitter dark mode

### ISSUE THREAD

**Issue by catleeball** [jordanpemberton/ReadingBuddies#1]
Issue mentioned in twitter comments:

- https://twitter.com/muddyboue/status/1434621947871170577
- https://twitter.com/muddyboue/status/1434622384087130113

It looks like a setting in the extension turns the Twitter sidebars white while in dark mode.

Asked the user if they could post their extension settings.

![image](https://user-images.githubusercontent.com/43632885/132142513-2f2cc5c4-265c-4b2a-b37a-426906530e89.png)

**Comment by jordanpemberton** [comment]
More info via @muddyboue: "This happens no matter what settings I have. It even happens if I have the extension disabled. Only way to get rid of it is to uninstall the extension entirely."

Problem: New release is not reverting style properties correctly when off or disabled, and style changes can only be corrected by uninstalling the extension.

Action: Submitted rollback to Chrome web store 9/5/21, waiting on approval. Correcting code.

**Comment by jordanpemberton** [comment]
This bug should be fixed in version 0.22, which is currently pending approval to be published to Chrome Web Store.
